version: "3.8"

services:
  postgresdb:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    networks:
      - back-tier

  app:
    depends_on:
      - postgresdb
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: express-api
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=$POSTGRES_HOST
      - DB_USER=$POSTGRES_USER
      - DB_PASSWORD=$POSTGRES_PASSWORD
      - DB_NAME=$POSTGRES_DB
      - DB_PORT=$POSTGRES_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
      - /app/node_modules
    command:
      sh -c "/app/wait-for-it.sh postgresdb:$POSTGRES_DOCKER_PORT -- npm run migrate &&
      /app/node_modules/.bin/nodemon --legacy-watch /app/src/index.js"
    networks:
      - back-tier

networks:
  back-tier:
    driver: bridge
