version: "3.8"

services:
  mysqldb:
    image: mysql:8.3.0
    container_name: mysql-db
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT

  app:
    depends_on:
      - mysqldb
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: express-api
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=$MYSQLDB_HOST
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    command:
      sh -c "npm i && /app/wait-for-it.sh mysqldb:$MYSQLDB_DOCKER_PORT --
      /app/node_modules/.bin/nodemon --legacy-watch /app/src/index.js"
