CREATE DATABASE IF NOT EXISTS hikenet;
USE hikenet;

CREATE TABLE IF NOT EXISTS USERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255),
    firstname VARCHAR(255),
    lastname VARCHAR(255),
    mail VARCHAR(255),
    isAdmin BOOLEAN
);
